# : Manager [[[

[mgr]
cwd = { fg = "#e1e2e9" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#e272ff", bg = "#e272ff" }
marker_cut      = { fg = "#f7d8ff", bg = "#f7d8ff" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#dabde2", bg = "#dabde2" }

# Count
count_copied   = { fg = "#271430", bg = "#f7d8ff" }
count_cut      = { fg = "#271430", bg = "#f7d8ff" }
count_selected = { fg = "#00315e", bg = "#dabde2" }

# Border
border_symbol = "│"
border_style  = { fg = "#a5c8ff" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "█", close = "█" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#a5c8ff", bold = true, bg = "#111318" }
inactive  = { fg = "#bcc7dc", bg = "#111318" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#a5c8ff", fg = "#00315e", bold = true }
normal_alt  = { bg = "#43474e", fg = "#c3c6cf" }

# Select mode
select_main = { bg = "#bcc7dc", fg = "#263141", bold = true }
select_alt  = { bg = "#43474e", fg = "#c3c6cf" }

# Unset mode
unset_main = { bg = "#dabde2", fg = "#3d2946", bold = true }
unset_alt  = { bg = "#43474e", fg = "#c3c6cf" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Permissions
perm_type  = { fg = "#5873a8" }
perm_write = { fg = "#9e53b3" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#d83fff" }
perm_sep   = { fg = "#3b7fff" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#a5c8ff", bg = "#37393e" }
progress_error  = { fg = "#ffb4ab", bg = "#37393e" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#37393e" }
cand = { fg = "#a5c8ff" }
rest = { fg = "#00315e" }
desc = { fg = "#e1e2e9" }
separator = " ▶ "
separator_style = { fg = "#e1e2e9" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#dabde2" }
title_warn  = { fg = "#a5c8ff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#a5c8ff" }
active = { fg = "#dabde2", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#a5c8ff" }
value  = { fg = "#e1e2e9" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#a5c8ff", bg = "#00315e" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#a5c8ff" }
title   = {}
hovered = { fg = "#f7d8ff", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#e1e2e9" }
run    = { fg = "#e1e2e9" }
footer = { fg = "#263141", bg = "#bcc7dc" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { url = "*", is = "orphan", bg = "#93000a" },
    { url = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#e1e2e9" },
    { url = "*/", fg = "#a5c8ff" },
]

# : ]]]
conds = [
	# Special files
	{ if = "orphan", text = "", fg = "#a5c8ff" },
	{ if = "link", text = "", fg = "#a5c8ff" },
	{ if = "block", text = "", fg = "#a5c8ff" },
	{ if = "char", text = "", fg = "#a5c8ff" },
	{ if = "fifo", text = "", fg = "#a5c8ff" },
	{ if = "sock", text = "", fg = "#a5c8ff" },
	{ if = "sticky", text = "", fg = "#a5c8ff" },
	{ if = "dummy", text = "", fg = "#a5c8ff" },

	# Fallback
	{ if = "dir", text = "", fg = "#a5c8ff" },
	{ if = "exec", text = "", fg = "#a5c8ff" },
	{ if = "!dir", text = "", fg = "#a5c8ff" },
]
# : }}}
