# : Manager [[[

[mgr]
cwd = { fg = "#e3e1e9" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#ff70e3", bg = "#ff70e3" }
marker_cut      = { fg = "#ffd6f7", bg = "#ffd6f7" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#e2bbdb", bg = "#e2bbdb" }

# Count
count_copied   = { fg = "#2b122a", bg = "#ffd6f7" }
count_cut      = { fg = "#2b122a", bg = "#ffd6f7" }
count_selected = { fg = "#1c2d61", bg = "#e2bbdb" }

# Border
border_symbol = "│"
border_style  = { fg = "#b5c4ff" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "█", close = "█" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#b5c4ff", bold = true, bg = "#121318" }
inactive  = { fg = "#c1c5dd", bg = "#121318" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#b5c4ff", fg = "#1c2d61", bold = true }
normal_alt  = { bg = "#45464f", fg = "#c6c6d0" }

# Select mode
select_main = { bg = "#c1c5dd", fg = "#2b3042", bold = true }
select_alt  = { bg = "#45464f", fg = "#c6c6d0" }

# Unset mode
unset_main = { bg = "#e2bbdb", fg = "#432740", bold = true }
unset_alt  = { bg = "#45464f", fg = "#c6c6d0" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Permissions
perm_type  = { fg = "#5e69a7" }
perm_write = { fg = "#b450a2" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#ff3dd9" }
perm_sep   = { fg = "#4262ff" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#b5c4ff", bg = "#38393f" }
progress_error  = { fg = "#ffb4ab", bg = "#38393f" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#38393f" }
cand = { fg = "#b5c4ff" }
rest = { fg = "#1c2d61" }
desc = { fg = "#e3e1e9" }
separator = " ▶ "
separator_style = { fg = "#e3e1e9" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#e2bbdb" }
title_warn  = { fg = "#b5c4ff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#b5c4ff" }
active = { fg = "#e2bbdb", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#b5c4ff" }
value  = { fg = "#e3e1e9" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#b5c4ff", bg = "#1c2d61" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#b5c4ff" }
title   = {}
hovered = { fg = "#ffd6f7", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#e3e1e9" }
run    = { fg = "#e3e1e9" }
footer = { fg = "#2b3042", bg = "#c1c5dd" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { url = "*", is = "orphan", bg = "#93000a" },
    { url = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#e3e1e9" },
    { url = "*/", fg = "#b5c4ff" },
]

# : ]]]
conds = [
	# Special files
	{ if = "orphan", text = "", fg = "#b5c4ff" },
	{ if = "link", text = "", fg = "#b5c4ff" },
	{ if = "block", text = "", fg = "#b5c4ff" },
	{ if = "char", text = "", fg = "#b5c4ff" },
	{ if = "fifo", text = "", fg = "#b5c4ff" },
	{ if = "sock", text = "", fg = "#b5c4ff" },
	{ if = "sticky", text = "", fg = "#b5c4ff" },
	{ if = "dummy", text = "", fg = "#b5c4ff" },

	# Fallback
	{ if = "dir", text = "", fg = "#b5c4ff" },
	{ if = "exec", text = "", fg = "#b5c4ff" },
	{ if = "!dir", text = "", fg = "#b5c4ff" },
]
# : }}}
