cursor            #ebc06c
cursor_text_color #402d00

foreground            #ebe1d4
background            #120e07
selection_foreground  #3b2f15
selection_background  #d9c4a0
url_color             #d9c4a0

#: black 000000 767676
color0  #17130b
color8  #3a342b
#: red cc0403 f2201f
color1  #060606
color9  #57514e
#: green 19cb00 23fd00
color2  #d9c4a0
color10 #f6e0bb
#: yellow cecb00 fffd00
color3  #b2cfa8
color11 #cdebc3
#: blue 0d73cc 1a8fff
color4  #5d4200
color12 #ebc06c
#: magenta cb1ed1 fd28ff
color5  #53452a
color13 #d9c4a0
#: cyan 0dcdcd 14ffff
color6  #344d2f
color14 #b2cfa8
#: white dddddd ffffff
color7  #d1c5b4
color15 #ebe1d4

mark1_foreground #261900
mark1_background #ffdea3
mark2_foreground #251a04
mark2_background #f6e0bb
mark3_foreground #092007
mark3_background #cdebc3

active_tab_foreground #402d00
active_tab_background #ebc06c
inactive_tab_foreground #ffdea3
inactive_tab_background #5d4200

active_border_color #ebc06c
inactive_border_color #402d00
# bell_border_color #ff5a00
