cursor            #ffb68a
cursor_text_color #522300

foreground            #f0dfd7
background            #140d08
selection_foreground  #432b1c
selection_background  #e5bfa9
url_color             #e5bfa9

#: black 000000 767676
color0  #1a120d
color8  #3d332d
#: red cc0403 f2201f
color1  #2f2d2e
color9  #7d787c
#: green 19cb00 23fd00
color2  #e5bfa9
color10 #ffdbc8
#: yellow cecb00 fffd00
color3  #cbc992
color11 #e8e5ac
#: blue 0d73cc 1a8fff
color4  #6f3811
color12 #ffb68a
#: magenta cb1ed1 fd28ff
color5  #5c4131
color13 #e5bfa9
#: cyan 0dcdcd 14ffff
color6  #49491e
color14 #cbc992
#: white dddddd ffffff
color7  #d7c2b8
color15 #f0dfd7

mark1_foreground #321300
mark1_background #ffdbc8
mark2_foreground #2b1709
mark2_background #ffdbc8
mark3_foreground #1d1d00
mark3_background #e8e5ac

active_tab_foreground #522300
active_tab_background #ffb68a
inactive_tab_foreground #ffdbc8
inactive_tab_background #6f3811

active_border_color #ffb68a
inactive_border_color #522300
# bell_border_color #ff5a00
