cursor            #ffffff
cursor_text_color #1b1b1b

foreground            #e2e2e2
background            #0e0e0e
selection_foreground  #1b1b1b
selection_background  #c6c6c6
url_color             #c6c6c6

#: black 000000 767676
color0  #131313
color8  #353535
#: red cc0403 f2201f
color1  #2d302d
color9  #787e78
#: green 19cb00 23fd00
color2  #ababab
color10 #c6c6c6
#: yellow cecb00 fffd00
color3  #474747
color11 #5e5e5e
#: blue 0d73cc 1a8fff
color4  #e2e2e2
color12 #ffffff
#: magenta cb1ed1 fd28ff
color5  #3b3b3b
color13 #c6c6c6
#: cyan 0dcdcd 14ffff
color6  #e2e2e2
color14 #e2e2e2
#: white dddddd ffffff
color7  #c6c6c6
color15 #e2e2e2

mark1_foreground #ffffff
mark1_background #5e5e5e
mark2_foreground #1b1b1b
mark2_background #c6c6c6
mark3_foreground #ffffff
mark3_background #5e5e5e

active_tab_foreground #1b1b1b
active_tab_background #ffffff
inactive_tab_foreground #000000
inactive_tab_background #d4d4d4

active_border_color #ffffff
inactive_border_color #1b1b1b
# bell_border_color #ff5a00
