-- Matugen → Neovim theme (mini.base16)
-- Generated by matugen. Do not edit this file manually.
--
-- This template maps Material You roles to a Base16 palette that works well
-- in Neovim (including Treesitter, LSP diagnostics, LazyVim UI, etc.).

local ok, base16 = pcall(require, "mini.base16")
if not ok then
  vim.notify("mini.base16 not installed — matugen theme skipped", vim.log.levels.WARN)
  return
end

base16.setup({
  palette = {
    base00 = "{{colors.background.default.hex}}",                    -- bg
    base01 = "{{colors.surface_container_lowest.default.hex}}",      -- bg alt / statusline
    base02 = "{{colors.surface_container_low.default.hex}}",         -- selection bg
    base03 = "{{colors.outline_variant.default.hex}}",               -- comments, invisibles
    base04 = "{{colors.on_surface_variant.default.hex}}",            -- dark fg / line numbers
    base05 = "{{colors.on_surface.default.hex}}",                    -- default fg
    base06 = "{{colors.inverse_on_surface.default.hex}}",            -- light fg
    base07 = "{{colors.surface_bright.default.hex}}",                -- bright bg / cursorline?

    -- Accents (Material You tuned)
    base08 = "{{colors.tertiary.default.hex | lighten: -5}}",        -- variables, tags, errors
    base09 = "{{colors.tertiary.default.hex}}",                      -- constants, numbers
    base0A = "{{colors.secondary.default.hex}}",                     -- classes, types, attributes
    base0B = "{{colors.primary.default.hex}}",                       -- strings, git added
    base0C = "{{colors.tertiary_container.default.hex}}",            -- regex, escapes, git modified
    base0D = "{{colors.primary_container.default.hex}}",             -- functions, methods, git deleted?
    base0E = "{{colors.secondary_container.default.hex}}",           -- keywords, storage, git changed
    base0F = "{{colors.secondary.default.hex | lighten: -12}}",      -- deprecated, embedded
  },
  use_cterm = false,
  plugins = { default = true },   -- auto-skin a ton of plugins (lualine, telescope, treesitter, etc.)
})

-- ------------------------------------------------------------------
-- Targeted polish (these survive mini.base16 and look good with Material You)
-- ------------------------------------------------------------------

-- Selection stands out nicely
vim.api.nvim_set_hl(0, "Visual", {
  bg = "{{colors.primary_container.default.hex}}",
  fg = "{{colors.on_primary_container.default.hex}}",
})

-- Comments are subtle + italic (very common preference)
vim.api.nvim_set_hl(0, "Comment", {
  fg = "{{colors.outline.default.hex}}",
  italic = true,
})
vim.api.nvim_set_hl(0, "@comment", {
  fg = "{{colors.outline.default.hex}}",
  italic = true,
})

-- Strings pop a bit more than the default base0B
vim.api.nvim_set_hl(0, "String", {
  fg = "{{colors.tertiary.default.hex | lighten: -15}}",
})
vim.api.nvim_set_hl(0, "@string", {
  fg = "{{colors.tertiary.default.hex | lighten: -15}}",
})

-- Make function calls a little distinct
vim.api.nvim_set_hl(0, "Function", {
  fg = "{{colors.secondary.default.hex}}",
})
vim.api.nvim_set_hl(0, "@function", {
  fg = "{{colors.secondary.default.hex}}",
})
vim.api.nvim_set_hl(0, "@function.call", {
  fg = "{{colors.secondary.default.hex}}",
})

-- Keywords a touch more vibrant
vim.api.nvim_set_hl(0, "Keyword", {
  fg = "{{colors.inverse_primary.default.hex}}",
})

-- Diagnostics (use the proper semantic colors from matugen)
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "{{colors.error.default.hex}}" })
vim.api.nvim_set_hl(0, "DiagnosticWarn",  { fg = "{{colors.tertiary.default.hex}}" })
vim.api.nvim_set_hl(0, "DiagnosticInfo",  { fg = "{{colors.primary.default.hex}}" })
vim.api.nvim_set_hl(0, "DiagnosticHint",  { fg = "{{colors.secondary.default.hex}}" })

-- ------------------------------------------------------------------
-- Live-reload helpers (lualine, bufferline, etc. often need a kick)
-- ------------------------------------------------------------------
pcall(function() require("lualine").setup({}) end)

-- If you use bufferline, uncomment:
-- pcall(function() require("bufferline").setup({}) end)

-- Optional: make the cursorline/subtle background changes feel nicer
vim.api.nvim_set_hl(0, "CursorLine", {
  bg = "{{colors.surface_container_low.default.hex}}",
})

-- You can keep adding your own nvim_set_hl overrides here as you tune.
