#!/usr/bin/env bash
# save-monitor-layout.sh
# Launch a Wayland display GUI (wdisplays), wait for you to finish arranging,
# then save the current layout as your active ~/.config/hypr/conf/monitor.conf.
#
# Usage:
#   save-monitor-layout.sh                 # launch wdisplays, configure, close → save
#   save-monitor-layout.sh --no-gui        # just capture whatever is currently active (no GUI)
#   save-monitor-layout.sh --dry-run       # show what would be written, don't touch files
#
# Requirements: hyprctl, jq, wdisplays (or any other GUI you prefer)

set -euo pipefail

MONITOR_CONF="$HOME/.config/hypr/conf/monitor.conf"
BACKUP_DIR="$HOME/.config/hypr/conf/monitors/bak"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
DRY_RUN=false
LAUNCH_GUI=true

# Parse args
while [[ $# -gt 0 ]]; do
    case "$1" in
        --no-gui)
            LAUNCH_GUI=false
            shift
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        -h|--help)
            sed -n '2,18p' "$0"
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

mkdir -p "$BACKUP_DIR"

# --- Launch the GUI if requested ---
if $LAUNCH_GUI; then
    if ! command -v wdisplays >/dev/null 2>&1; then
        notify-send -u critical "save-monitor-layout" "wdisplays not found. Install it or use --no-gui."
        echo "Error: wdisplays not found in PATH" >&2
        exit 1
    fi

    notify-send "Monitor Layout" "wdisplays is open.\nArrange your monitors, then CLOSE the window to save." -t 6000

    # Launch and wait for the user to close it
    wdisplays &

    # Give it a moment to appear, then wait for the process to exit
    sleep 0.8
    wait $! 2>/dev/null || true

    # Small grace period for Hyprland to apply the new positions
    sleep 0.6
fi

# --- Capture current state from Hyprland ---
if ! command -v hyprctl >/dev/null 2>&1; then
    echo "Error: hyprctl not found" >&2
    exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
    echo "Error: jq is required but not installed" >&2
    exit 1
fi

MONITOR_JSON=$(hyprctl monitors -j 2>/dev/null)
if [[ -z "$MONITOR_JSON" || "$MONITOR_JSON" == "null" ]]; then
    echo "Error: Could not get monitor info from hyprctl" >&2
    exit 1
fi

# Count active (non-disabled) monitors
ACTIVE_COUNT=$(echo "$MONITOR_JSON" | jq '[.[] | select(.disabled == false or .disabled == null)] | length')

if [[ "$ACTIVE_COUNT" -eq 0 ]]; then
    echo "Error: No active monitors reported by Hyprland" >&2
    exit 1
fi

# --- Generate the new monitor.conf content ---
# We prefer "desc:" matching because connector names (DP-1, DVI-I-1, etc.) can change
# across boots, docks, GPU resets, etc. Your workspaces.conf already uses desc: correctly.

HEADER="# =====================================================
# Monitor Configuration - Saved $(date '+%Y-%m-%d %H:%M:%S')
# =====================================================
# Generated by save-monitor-layout.sh
# Using desc: matching for maximum stability (connector names can change).
#
# After editing manually, run:  hyprctl reload
# Or use:  Super + M  (if you have monitor-rofi.sh bound)
"

# Build one "monitor = desc:..." line per active monitor.
# Sort by current x position so the file reads left-to-right.
BODY=$(echo "$MONITOR_JSON" | jq -r '
  [.[] | select(.disabled == false or .disabled == null)]
  | sort_by(.x)
  | .[] 
  | "monitor = desc:\(.description | @sh), \(.width)x\(.height)@\(.refreshRate | floor), \(.x)x\(.y), \(.scale)"
    + (if .transform != 0 then ", transform, \(.transform)" else "" end)
')

# Also emit a safe fallback line at the end (Hyprland will ignore it for known monitors)
FOOTER="
# Fallback for any unknown/new monitors
monitor = , preferred, auto, 1
"

NEW_CONTENT="${HEADER}
${BODY}
${FOOTER}"

# --- Dry run mode ---
if $DRY_RUN; then
    echo "=== DRY RUN: Would write the following to ${MONITOR_CONF} ==="
    echo "$NEW_CONTENT"
    echo "=== End dry run ==="
    exit 0
fi

# --- Backup current config ---
if [[ -f "$MONITOR_CONF" ]]; then
    cp -f "$MONITOR_CONF" "${BACKUP_DIR}/monitor.conf.${TIMESTAMP}.bak"
    echo "Backed up current config → ${BACKUP_DIR}/monitor.conf.${TIMESTAMP}.bak"
fi

# --- Write the new config ---
echo "$NEW_CONTENT" > "$MONITOR_CONF"
echo "Wrote new monitor configuration to ${MONITOR_CONF}"

# --- Reload Hyprland so the layout takes effect immediately ---
if hyprctl reload >/dev/null 2>&1; then
    notify-send "Monitor Layout Saved" "✅ Saved ${ACTIVE_COUNT} monitor(s) to monitor.conf\nHyprland reloaded." -t 4000
    echo "Hyprland reloaded."
else
    notify-send "Monitor Layout Saved" "✅ Saved to monitor.conf\n(Reload failed or not running under Hyprland)" -u low
    echo "Warning: hyprctl reload did not succeed (are you outside a Hyprland session?)"
fi

echo
echo "Current layout captured:"
echo "$BODY"
