#!/bin/bash
# ===================================================================
# Update SDDM (sugar-candy theme) background from the full-screen
# blurred wallpaper generated by the Super+W selector.
#
# Usage:
#   update-sddm-wallpaper.sh [source_image.png]
#
# If no arg, uses the standard full blurred cache file.
# Requires sudo (or pkexec) the first time to write into /usr/share/sddm/themes.
# ===================================================================

set -euo pipefail

SOURCE="${1:-$HOME/.config/settings/cache/blurred_wallpaper_full.png}"
THEME_DIR="/usr/share/sddm/themes/sugar-candy"
TARGET_BG_DIR="$THEME_DIR/Backgrounds"
TARGET_BG="$TARGET_BG_DIR/sddm-blurred.png"
THEME_CONF="$THEME_DIR/theme.conf"
SDDM_USER="sddm"

if [ ! -f "$SOURCE" ]; then
    echo "SDDM wallpaper: source not found: $SOURCE" >&2
    exit 0
fi

if [ ! -d "$THEME_DIR" ]; then
    echo "SDDM wallpaper: sugar-candy theme not installed at $THEME_DIR" >&2
    exit 0
fi

echo ":: Updating SDDM background from $SOURCE"

# Ensure target dir exists
sudo mkdir -p "$TARGET_BG_DIR" 2>/dev/null || true

# Copy / convert to png (sugar-candy accepts png)
if command -v magick >/dev/null 2>&1; then
    sudo magick "$SOURCE" -quality 90 "$TARGET_BG" 2>/dev/null || \
    sudo cp -f "$SOURCE" "$TARGET_BG" 2>/dev/null || true
else
    sudo cp -f "$SOURCE" "$TARGET_BG" 2>/dev/null || true
fi

# Make world-readable (SDDM greeter runs with limited privs)
sudo chmod 644 "$TARGET_BG" 2>/dev/null || true

# Grant sddm user execute on ~ if needed (for some dynamic setups, harmless)
if id "$SDDM_USER" >/dev/null 2>&1; then
    sudo setfacl -m u:$SDDM_USER:x "$HOME" 2>/dev/null || true
fi

# Update theme.conf to use the new blurred background
if [ -f "$THEME_CONF" ]; then
    # Use a distinct name so we don't clobber any manual Backgrounds/sddm.jpg
    sudo sed -i 's|^Background=.*|Background="Backgrounds/sddm-blurred.png"|' "$THEME_CONF" 2>/dev/null || true
    echo ":: SDDM theme.conf updated to use blurred wallpaper"
else
    echo "WARNING: $THEME_CONF not found" >&2
fi

# Optional: also update ScreenWidth/ScreenHeight if you want, but usually leave it
# (sugar-candy uses it only as a hint for scaling calculations)

echo ":: SDDM login background updated (will apply on next login/reboot)"
notify-send "SDDM" "Login screen wallpaper updated" -t 2000 2>/dev/null || true
