#!/bin/bash
# Waybar Theme Switcher
# Usage: waybar-theme.sh [matugen|gruvbox|catppuccin-mocha|none-dark|none-light]

THEME=${1:-matugen}
WAYBAR_DIR="$HOME/.config/waybar"

case "$THEME" in
    matugen)
        ln -sf "$WAYBAR_DIR/themes/matugen/colors.css" "$WAYBAR_DIR/themes/active/colors.css"
        echo "Switched to Matugen (rainbow)"
        ;;
    gruvbox)
        ln -sf "$WAYBAR_DIR/themes/gruvbox/colors.css" "$WAYBAR_DIR/themes/active/colors.css"
        echo "Switched to Gruvbox"
        ;;
    catppuccin-mocha)
        ln -sf "$WAYBAR_DIR/themes/catppuccin-mocha/colors.css" "$WAYBAR_DIR/themes/active/colors.css"
        echo "Switched to Catppuccin Mocha"
        ;;
    none-dark)
        # Generated by palette.sh "None" mode (whitest white text)
        if [ -f "$WAYBAR_DIR/colors/matugen.css" ]; then
            cp "$WAYBAR_DIR/colors/matugen.css" "$WAYBAR_DIR/themes/active/colors.css"
        fi
        echo "Switched to None-Dark (Matugen extreme white text)"
        ;;
    none-light)
        # Generated by palette.sh "None" mode (darkest black text)
        if [ -f "$WAYBAR_DIR/colors/matugen.css" ]; then
            cp "$WAYBAR_DIR/colors/matugen.css" "$WAYBAR_DIR/themes/active/colors.css"
        fi
        echo "Switched to None-Light (Matugen extreme dark text)"
        ;;
    *)
        echo "Usage: $0 [matugen|gruvbox|catppuccin-mocha|none-dark|none-light]"
        exit 1
        ;;
esac

pkill waybar 2>/dev/null || true
sleep 0.2
waybar &
