
$image = wallhaven-3ql3x6.jpg
$background = rgba(12140eff)

$image = wallhaven-3ql3x6.jpg
$error = rgba(ffb4abff)

$image = wallhaven-3ql3x6.jpg
$error_container = rgba(93000aff)

$image = wallhaven-3ql3x6.jpg
$inverse_on_surface = rgba(2f312aff)

$image = wallhaven-3ql3x6.jpg
$inverse_primary = rgba(4f6628ff)

$image = wallhaven-3ql3x6.jpg
$inverse_surface = rgba(e3e3d8ff)

$image = wallhaven-3ql3x6.jpg
$on_background = rgba(e3e3d8ff)

$image = wallhaven-3ql3x6.jpg
$on_error = rgba(690005ff)

$image = wallhaven-3ql3x6.jpg
$on_error_container = rgba(ffdad6ff)

$image = wallhaven-3ql3x6.jpg
$on_primary = rgba(233600ff)

$image = wallhaven-3ql3x6.jpg
$on_primary_container = rgba(d1eca0ff)

$image = wallhaven-3ql3x6.jpg
$on_primary_fixed = rgba(131f00ff)

$image = wallhaven-3ql3x6.jpg
$on_primary_fixed_variant = rgba(384d12ff)

$image = wallhaven-3ql3x6.jpg
$on_secondary = rgba(2b331dff)

$image = wallhaven-3ql3x6.jpg
$on_secondary_container = rgba(dde6c6ff)

$image = wallhaven-3ql3x6.jpg
$on_secondary_fixed = rgba(171e0aff)

$image = wallhaven-3ql3x6.jpg
$on_secondary_fixed_variant = rgba(414a32ff)

$image = wallhaven-3ql3x6.jpg
$on_surface = rgba(e3e3d8ff)

$image = wallhaven-3ql3x6.jpg
$on_surface_variant = rgba(c5c8b9ff)

$image = wallhaven-3ql3x6.jpg
$on_tertiary = rgba(013733ff)

$image = wallhaven-3ql3x6.jpg
$on_tertiary_container = rgba(bcece5ff)

$image = wallhaven-3ql3x6.jpg
$on_tertiary_fixed = rgba(00201dff)

$image = wallhaven-3ql3x6.jpg
$on_tertiary_fixed_variant = rgba(1f4e4aff)

$image = wallhaven-3ql3x6.jpg
$outline = rgba(8f9285ff)

$image = wallhaven-3ql3x6.jpg
$outline_variant = rgba(45483dff)

$image = wallhaven-3ql3x6.jpg
$primary = rgba(b5d086ff)

$image = wallhaven-3ql3x6.jpg
$primary_container = rgba(384d12ff)

$image = wallhaven-3ql3x6.jpg
$primary_fixed = rgba(d1eca0ff)

$image = wallhaven-3ql3x6.jpg
$primary_fixed_dim = rgba(b5d086ff)

$image = wallhaven-3ql3x6.jpg
$scrim = rgba(000000ff)

$image = wallhaven-3ql3x6.jpg
$secondary = rgba(c1caabff)

$image = wallhaven-3ql3x6.jpg
$secondary_container = rgba(414a32ff)

$image = wallhaven-3ql3x6.jpg
$secondary_fixed = rgba(dde6c6ff)

$image = wallhaven-3ql3x6.jpg
$secondary_fixed_dim = rgba(c1caabff)

$image = wallhaven-3ql3x6.jpg
$shadow = rgba(000000ff)

$image = wallhaven-3ql3x6.jpg
$source_color = rgba(334b04ff)

$image = wallhaven-3ql3x6.jpg
$surface = rgba(12140eff)

$image = wallhaven-3ql3x6.jpg
$surface_bright = rgba(383a32ff)

$image = wallhaven-3ql3x6.jpg
$surface_container = rgba(1e2019ff)

$image = wallhaven-3ql3x6.jpg
$surface_container_high = rgba(292b23ff)

$image = wallhaven-3ql3x6.jpg
$surface_container_highest = rgba(33362eff)

$image = wallhaven-3ql3x6.jpg
$surface_container_low = rgba(1a1c15ff)

$image = wallhaven-3ql3x6.jpg
$surface_container_lowest = rgba(0d0f09ff)

$image = wallhaven-3ql3x6.jpg
$surface_dim = rgba(12140eff)

$image = wallhaven-3ql3x6.jpg
$surface_tint = rgba(b5d086ff)

$image = wallhaven-3ql3x6.jpg
$surface_variant = rgba(45483dff)

$image = wallhaven-3ql3x6.jpg
$tertiary = rgba(a0d0c9ff)

$image = wallhaven-3ql3x6.jpg
$tertiary_container = rgba(1f4e4aff)

$image = wallhaven-3ql3x6.jpg
$tertiary_fixed = rgba(bcece5ff)

$image = wallhaven-3ql3x6.jpg
$tertiary_fixed_dim = rgba(a0d0c9ff)

