[General]

Background="/home/.local/bin/default_wp.png"
DimBackgroundImage="0.0"                        ##  0-1 / Use to darken your background image on the fly.

ScaleImageCropped="true"

ScreenWidth="1440"
ScreenHeight="900"                              ## Adjust to your resolution to help SDDM speed up on calculations

## [Design Customizations]
## [Blur Settings]
FullBlur="false"
PartialBlur="true"
BlurRadius="100"

HaveFormBackground="false"               ## if PartialBlur true then HaveFormBackground will be partially transparent
                                         ## Anything above 100 > strong might slow rendering. 0 is like setting false for any blur.
FormPosition="left"                      ## Roughly 1/3 of screen estate. Can be left, center or right.
BackgroundImageHAlignment="center"       ## Horizontal position of the background picture relative to its visible area. Applies when ScaleImageCropped is set to false or when HaveFormBackground is set to true and FormPosition is either left or right. Can be left, center or right; defaults to center if none is passed.
BackgroundImageVAlignment="center"       ## As before but for the vertical position of the background picture relative to its visible area.

MainColor="white"                        ## Can be HEX or Qt names (e.g. red/salmon). https://doc.qt.io/qt-5/qml-color.html
AccentColor="#fb884f"                    ## Elements in focus/hover/pressed. Should be contrasting to the background and Main
BackgroundColor="#444"                   ## Used for the user and session selection background as well as for ScreenPadding and FormBackground when either is true. If PartialBlur and FormBackground are both enabled this color will blend with the blur effect.
OverrideLoginButtonTextColor=""          ## The text of the login button may become difficult to read depending on your color choices. Use this option to set it independently for legibility.
InterfaceShadowSize="6"                  ## Integer used as multiplier. Size of the shadow behind the user and session selection background. Decrease or increase if it looks bad on your background. Initial render can be slow no values above 5-7.

InterfaceShadowOpacity="0.7"             ## Double between 0 and 1. Alpha channel of the shadow behind the user and session selection background. Decrease or increase if it looks bad on your background.
RoundCorners="20"
ScreenPadding="0"
Font="ShureTechMono Nerd Fot Regular"
FontSize=""

## [Interface Behavior]
ForceRightToLeft="false"
ForceLastUser="true"
ForcePasswordFocus="true"
ForceHideCompletePassword="false"
ForceHideVirtualKeyboardButton="true"
ForceHideSystemButtons="false"
AllowEmptyPassword="false"
AllowBadUsernames="false"

## [Locale Settings]
Locale=""
HourFormat="HH:mm"
DateFormat="dddd, d of MMMM"
## [Translations]
HeaderText="Sup My G?"

## SDDM may lack proper translation for every element. Suger defaults to SDDM translations. Please help translate SDDM as much as possible for your language: https://github.com/sddm/sddm/wiki/Localization. These are in order as they appear on screen.
TranslatePlaceholderUsername="user"
TranslatePlaceholderPassword="password"
TranslateShowPassword="Show Password"
TranslateLogin="login"
TranslateLoginFailedWarning="Login Failed!!"
TranslateCapslockWarning="Caps Lock Enagled!"
TranslateSession=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateVirtualKeyboardButton=""

