--ozone-platform=wayland
--enable-features=AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoDecodeLinuxGL,VaapiIgnoreDriverChecks,AcceleratedVideoEncoder,WaylandWindowDecorations
--use-gl=desktop
--ignore-gpu-blocklist
