cursor            #ddc66e
cursor_text_color #3a3000

foreground            #e9e2d4
background            #100e07
selection_foreground  #373016
selection_background  #d2c6a1
url_color             #d2c6a1

#: black 000000 767676
color0  #16130b
color8  #38352b
#: red cc0403 f2201f
color1  #000000
color9  #4c4948
#: green 19cb00 23fd00
color2  #d2c6a1
color10 #efe2bc
#: yellow cecb00 fffd00
color3  #aad0b2
color11 #c6eccd
#: blue 0d73cc 1a8fff
color4  #544600
color12 #ddc66e
#: magenta cb1ed1 fd28ff
color5  #4e462a
color13 #d2c6a1
#: cyan 0dcdcd 14ffff
color6  #2c4e37
color14 #aad0b2
#: white dddddd ffffff
color7  #cdc6b4
color15 #e9e2d4

mark1_foreground #221b00
mark1_background #fae287
mark2_foreground #211b04
mark2_background #efe2bc
mark3_foreground #00210e
mark3_background #c6eccd

active_tab_foreground #3a3000
active_tab_background #ddc66e
inactive_tab_foreground #fae287
inactive_tab_background #544600

active_border_color #ddc66e
inactive_border_color #3a3000
# bell_border_color #ff5a00
