--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kirk/Pictures/Wallpapers/cat-astronaut.png"

-- Special
background="#101019"
foreground="#c3c3c5"
cursor="#c3c3c5"

-- Colors
color0="#101019"
color1="#887B91"
color2="#A594AA"
color3="#D5A6B4"
color4="#E7B4B2"
color5="#EAC6BA"
color6="#DABAC1"
color7="#c3c3c5"
color8="#5b5b70"
color9="#887B91"
color10="#A594AA"
color11="#D5A6B4"
color12="#E7B4B2"
color13="#EAC6BA"
color14="#DABAC1"
color15="#c3c3c5"
