[colors]
background = '#1010198e'
black = '#101019'
blue = '#887B91'
cursor = '#c3c3c5'
cyan = '#A594AA'
foreground = '#c3c3c5'
green = '#D5A6B4'
magenta = '#E7B4B2'
red = '#EAC6BA'
tabs = '#c3c3c5'
tabs-active = '#DABAC1'
white = '#c3c3c5'
yellow = '#c3c3c5'
dim-black = '#1010198e'
dim-blue = '#887B918e'
dim-cyan = '#A594AA8e'
dim-foreground = '#c3c3c58e'
dim-green = '#D5A6B48e'
dim-magenta = '#E7B4B28e'
dim-red = '#EAC6BA8e'
dim-white = '#DABAC18e'
dim-yellow = '#c3c3c58e'
light-black = '#887B91'
light-blue = '#A594AA'
light-cyan = '#D5A6B4'
light-foreground = '#E7B4B2'
light-green = '#EAC6BA'
light-magenta = '#DABAC1'
light-red = '#c3c3c5'
light-white = '#887B91'
light-yellow = '#A594AA'
