# Shell variables
# Generated by 'wal'
wallpaper="/home/kirk/Pictures/Wallpapers/cat-astronaut.png"

# Special
background='#101019'
foreground='#c3c3c5'
cursor='#c3c3c5'

# Colors
color0='#101019'
color1='#887B91'
color2='#A594AA'
color3='#D5A6B4'
color4='#E7B4B2'
color5='#EAC6BA'
color6='#DABAC1'
color7='#c3c3c5'
color8='#5b5b70'
color9='#887B91'
color10='#A594AA'
color11='#D5A6B4'
color12='#E7B4B2'
color13='#EAC6BA'
color14='#DABAC1'
color15='#c3c3c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
