foreground         #c3c3c5
background         #101019
background_opacity 1.0
cursor             #c3c3c5

active_tab_foreground     #101019
active_tab_background     #c3c3c5
inactive_tab_foreground   #c3c3c5
inactive_tab_background   #101019

active_border_color   #c3c3c5
inactive_border_color #101019
bell_border_color     #887B91

color0       #101019
color8       #5b5b70
color1       #887B91
color9       #887B91
color2       #A594AA
color10      #A594AA
color3       #D5A6B4
color11      #D5A6B4
color4       #E7B4B2
color12      #E7B4B2
color5       #EAC6BA
color13      #EAC6BA
color6       #DABAC1
color14      #DABAC1
color7       #c3c3c5
color15      #c3c3c5
