#!/bin/bash

# gum theme using pywal colors

# Confirm styles
export GUM_CONFIRM_PROMPT="? "
export GUM_CONFIRM_SELECTED_BACKGROUND="#E7B4B2"
export GUM_CONFIRM_SELECTED_FOREGROUND="#101019"
export GUM_CONFIRM_UNSELECTED_BACKGROUND="#101019"
export GUM_CONFIRM_UNSELECTED_FOREGROUND="#c3c3c5"

# Input styles
export GUM_INPUT_CURSOR_FOREGROUND="#c3c3c5"
export GUM_INPUT_PROMPT_FOREGROUND="#A594AA"
export GUM_INPUT_PLACEHOLDER_FOREGROUND="#5b5b70"
export GUM_INPUT_TEXT_FOREGROUND="#c3c3c5"
export GUM_INPUT_WIDTH=40

# Spinner styles
export GUM_SPIN_SPINNER_FOREGROUND="#DABAC1"

# Filter styles
export GUM_FILTER_INDICATOR_FOREGROUND="#EAC6BA"
export GUM_FILTER_SELECTED_PREFIX_FOREGROUND="#A594AA"
export GUM_FILTER_SELECTED_FOREGROUND="#c3c3c5"
export GUM_FILTER_UNSELECTED_PREFIX_FOREGROUND="#5b5b70"

# Choose styles
export GUM_CHOOSE_CURSOR_FOREGROUND="#E7B4B2"
export GUM_CHOOSE_SELECTED_FOREGROUND="#c3c3c5"
export GUM_CHOOSE_UNSELECTED_FOREGROUND="#5b5b70"

# Write styles
export GUM_WRITE_CURSOR_FOREGROUND="#c3c3c5"
export GUM_WRITE_PROMPT_FOREGROUND="#A594AA"
