-- Matugen → Neovim theme (mini.base16)
-- Generated by matugen. Do not edit this file manually.
--
-- This template maps Material You roles to a Base16 palette that works well
-- in Neovim (including Treesitter, LSP diagnostics, LazyVim UI, etc.).

local ok, base16 = pcall(require, "mini.base16")
if not ok then
  vim.notify("mini.base16 not installed — matugen theme skipped", vim.log.levels.WARN)
  return
end

base16.setup({
  palette = {
    base00 = "#141318",                    -- bg
    base01 = "#0e0e13",      -- bg alt / statusline
    base02 = "#1c1b20",         -- selection bg
    base03 = "#47464f",               -- comments, invisibles
    base04 = "#c9c5d0",            -- dark fg / line numbers
    base05 = "#e5e1e9",                    -- default fg
    base06 = "#313036",            -- light fg
    base07 = "#3a383e",                -- bright bg / cursorline?

    -- Accents (Material You tuned)
    base08 = "#e7a4c0",        -- variables, tags, errors
    base09 = "#ecb8ce",                      -- constants, numbers
    base0A = "#c8c3dc",                     -- classes, types, attributes
    base0B = "#c7bfff",                       -- strings, git added
    base0C = "#613b4d",            -- regex, escapes, git modified
    base0D = "#463f77",             -- functions, methods, git deleted?
    base0E = "#474459",           -- keywords, storage, git changed
    base0F = "#a59cc5",      -- deprecated, embedded
  },
  use_cterm = false,
  plugins = { default = true },   -- auto-skin a ton of plugins (lualine, telescope, treesitter, etc.)
})

-- ------------------------------------------------------------------
-- Targeted polish (these survive mini.base16 and look good with Material You)
-- ------------------------------------------------------------------

-- Selection stands out nicely
vim.api.nvim_set_hl(0, "Visual", {
  bg = "#463f77",
  fg = "#e4dfff",
})

-- Comments are subtle + italic (very common preference)
vim.api.nvim_set_hl(0, "Comment", {
  fg = "#928f99",
  italic = true,
})
vim.api.nvim_set_hl(0, "@comment", {
  fg = "#928f99",
  italic = true,
})

-- Strings pop a bit more than the default base0B
vim.api.nvim_set_hl(0, "String", {
  fg = "#dc7ca4",
})
vim.api.nvim_set_hl(0, "@string", {
  fg = "#dc7ca4",
})

-- Make function calls a little distinct
vim.api.nvim_set_hl(0, "Function", {
  fg = "#c8c3dc",
})
vim.api.nvim_set_hl(0, "@function", {
  fg = "#c8c3dc",
})
vim.api.nvim_set_hl(0, "@function.call", {
  fg = "#c8c3dc",
})

-- Keywords a touch more vibrant
vim.api.nvim_set_hl(0, "Keyword", {
  fg = "#5e5791",
})

-- Diagnostics (use the proper semantic colors from matugen)
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#ffb4ab" })
vim.api.nvim_set_hl(0, "DiagnosticWarn",  { fg = "#ecb8ce" })
vim.api.nvim_set_hl(0, "DiagnosticInfo",  { fg = "#c7bfff" })
vim.api.nvim_set_hl(0, "DiagnosticHint",  { fg = "#c8c3dc" })

-- ------------------------------------------------------------------
-- Live-reload helpers (lualine, bufferline, etc. often need a kick)
-- ------------------------------------------------------------------
pcall(function() require("lualine").setup({}) end)

-- If you use bufferline, uncomment:
-- pcall(function() require("bufferline").setup({}) end)

-- Optional: make the cursorline/subtle background changes feel nicer
vim.api.nvim_set_hl(0, "CursorLine", {
  bg = "#1c1b20",
})

-- You can keep adding your own nvim_set_hl overrides here as you tune.
