-- Matugen → Neovim theme (mini.base16)
-- Generated by matugen. Do not edit this file manually.
--
-- This template maps Material You roles to a Base16 palette that works well
-- in Neovim (including Treesitter, LSP diagnostics, LazyVim UI, etc.).

local ok, base16 = pcall(require, "mini.base16")
if not ok then
  vim.notify("mini.base16 not installed — matugen theme skipped", vim.log.levels.WARN)
  return
end

base16.setup({
  palette = {
    base00 = "#111418",                    -- bg
    base01 = "#0b0e13",      -- bg alt / statusline
    base02 = "#191c20",         -- selection bg
    base03 = "#43474e",               -- comments, invisibles
    base04 = "#c3c6cf",            -- dark fg / line numbers
    base05 = "#e1e2e8",                    -- default fg
    base06 = "#2e3035",            -- light fg
    base07 = "#37393e",                -- bright bg / cursorline?

    -- Accents (Material You tuned)
    base08 = "#cdabdb",        -- variables, tags, errors
    base09 = "#d8bde3",                      -- constants, numbers
    base0A = "#bbc7db",                     -- classes, types, attributes
    base0B = "#a2c9fe",                       -- strings, git added
    base0C = "#533f5f",            -- regex, escapes, git modified
    base0D = "#1d4875",             -- functions, methods, git deleted?
    base0E = "#3c4858",           -- keywords, storage, git changed
    base0F = "#93a6c6",      -- deprecated, embedded
  },
  use_cterm = false,
  plugins = { default = true },   -- auto-skin a ton of plugins (lualine, telescope, treesitter, etc.)
})

-- ------------------------------------------------------------------
-- Targeted polish (these survive mini.base16 and look good with Material You)
-- ------------------------------------------------------------------

-- Selection stands out nicely
vim.api.nvim_set_hl(0, "Visual", {
  bg = "#1d4875",
  fg = "#d3e4ff",
})

-- Comments are subtle + italic (very common preference)
vim.api.nvim_set_hl(0, "Comment", {
  fg = "#8d9199",
  italic = true,
})
vim.api.nvim_set_hl(0, "@comment", {
  fg = "#8d9199",
  italic = true,
})

-- Strings pop a bit more than the default base0B
vim.api.nvim_set_hl(0, "String", {
  fg = "#b887cc",
})
vim.api.nvim_set_hl(0, "@string", {
  fg = "#b887cc",
})

-- Make function calls a little distinct
vim.api.nvim_set_hl(0, "Function", {
  fg = "#bbc7db",
})
vim.api.nvim_set_hl(0, "@function", {
  fg = "#bbc7db",
})
vim.api.nvim_set_hl(0, "@function.call", {
  fg = "#bbc7db",
})

-- Keywords a touch more vibrant
vim.api.nvim_set_hl(0, "Keyword", {
  fg = "#38608f",
})

-- Diagnostics (use the proper semantic colors from matugen)
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#ffb4ab" })
vim.api.nvim_set_hl(0, "DiagnosticWarn",  { fg = "#d8bde3" })
vim.api.nvim_set_hl(0, "DiagnosticInfo",  { fg = "#a2c9fe" })
vim.api.nvim_set_hl(0, "DiagnosticHint",  { fg = "#bbc7db" })

-- ------------------------------------------------------------------
-- Live-reload helpers (lualine, bufferline, etc. often need a kick)
-- ------------------------------------------------------------------
pcall(function() require("lualine").setup({}) end)

-- If you use bufferline, uncomment:
-- pcall(function() require("bufferline").setup({}) end)

-- Optional: make the cursorline/subtle background changes feel nicer
vim.api.nvim_set_hl(0, "CursorLine", {
  bg = "#191c20",
})

-- You can keep adding your own nvim_set_hl overrides here as you tune.
