#!/bin/bash

# ================================================
# Hyprland Monitor Switcher with Rofi + nwg-displays support
# ================================================

MONITOR_OPTIONS_DIR="$HOME/.config/hypr/conf/monitors"
MONITOR_CONF="$HOME/.config/hypr/conf/monitor.conf"

mkdir -p "$MONITOR_OPTIONS_DIR"

if [ ! -d "$MONITOR_OPTIONS_DIR" ]; then
    notify-send "Hyprland Monitor Switcher" "Error: Could not create monitors directory!" -u critical
    exit 1
fi

# Build menu options
mapfile -t existing < <(ls -1 "$MONITOR_OPTIONS_DIR"/*.conf 2>/dev/null | xargs -n1 basename | sed 's/\.conf$//' | sort)

options=("➕ Create new from current setup (run nwg-displays)")
for conf in "${existing[@]}"; do
    options+=("$conf")
done

chosen=$(printf '%s\n' "${options[@]}" | rofi -dmenu \
    -i \
    -p "Monitor Configuration" \
    -mesg "Select setup or create new one" \
    -theme-str 'window {width: 500px;}' )

[ -z "$chosen" ] && exit 0

# === Handle "Create new" option ===
if [[ "$chosen" == "➕ Create new from current setup"* ]]; then
    notify-send "nwg-displays" "Opening display manager...\nConfigure your monitors, then close the window." -t 4000

    # Launch nwg-displays
    nwg-displays &

    # Wait for nwg-displays to close
    wait $!

    # Small delay to let changes apply
    sleep 0.8

    # Generate config from current hyprctl output
    notify-send "Saving configuration" "Generating new monitor config from current setup..."

    # Extract monitor lines
    config_content=$(hyprctl monitors -j | jq -r '
        .[] | 
        "monitor=\(.name),\(.width)x\(.height)@\(.refreshRate),\(.x)x\(.y),\(.scale)"
    ')

    if [ -z "$config_content" ]; then
        notify-send "Error" "Failed to get current monitor info" -u critical
        exit 1
    fi

    # Ask for a name for the new config
    new_name=$(rofi -dmenu -p "Name this configuration (no spaces)" \
        -mesg "Example: home-dual, office-triple, laptop-only" \
        -theme-str 'window {width: 450px;}')

    [ -z "$new_name" ] && exit 0

    # Sanitize name (remove invalid chars)
    new_name=$(echo "$new_name" | tr ' ' '-' | sed 's/[^a-zA-Z0-9_-]//g')

    new_file="$MONITOR_OPTIONS_DIR/${new_name}.conf"

    echo "# Generated by monitor-rofi.sh on $(date)" > "$new_file"
    echo "$config_content" >> "$new_file"

    notify-send "Success" "New config saved as:\n${new_name}.conf" -t 3000

    chosen="$new_name"   # so we can apply it below
fi

# === Apply the chosen configuration ===
selected_file="$MONITOR_OPTIONS_DIR/${chosen}.conf"

if [ ! -f "$selected_file" ]; then
    notify-send "Error" "Config file not found: ${chosen}.conf" -u critical
    exit 1
fi

# Backup current
if [ -f "$MONITOR_CONF" ]; then
    cp "$MONITOR_CONF" "${MONITOR_CONF}.bak"
fi

cp "$selected_file" "$MONITOR_CONF"

# Reload Hyprland
hyprctl reload

notify-send "Hyprland Monitor Switcher" "✅ Applied: ${chosen}\nHyprland reloaded" -u normal -t 4000
