-- hyprland.lua
-- Converted from ~/.config/hypr/hyprland.conf + active sourced modules
-- Target: Hyprland 0.55+ native Lua config (hl.* API)
--
-- Usage:
--   Hyprland will prefer hyprland.lua over hyprland.conf if both exist.
--   To test this conversion:
--     hyprctl dispatch exec "Hyprland --config ~/.config/hypr/hyprland.lua"
--   Or set it as default in your display manager / tty login script.
--
-- This is a best-effort conversion of the *active* configuration chain only.
-- All the variant presets (animations/*, decorations/*, etc.) were left out.
-- Scripts are referenced from the original ~/.config/hypr/scripts (no duplication).

-- === Path setup so requires work from SDDM ===
local config_dir = debug.getinfo(1, "S").source:match("^@(.*/)") or (os.getenv("HOME") .. "/.config/hypr/")
package.path = config_dir .. "?.lua;" .. config_dir .. "?/init.lua;" .. package.path
-- =============================================

-- Force fresh colors module on every evaluation (including hyprctl reload).
-- Without this, Lua's require cache would make matugen color updates invisible
-- until a full Hyprland restart.
package.loaded["colors.init"] = nil

-- Load colors early (same order as original) — now guaranteed fresh on reloads
local _ = require("colors.init").load()  -- result unused here; modules that need it call load() themselves

-- Load centralized fonts (single source: ~/.config/settings/fonts.sh)
local fonts = require("conf.fonts").load()

-- Make common paths available
local HOME = os.getenv("HOME") or ""
local SCRIPTS = HOME .. "/.config/hypr/scripts"

-- You can (and should) split further. All requires below are relative
-- to ~/.config/hypr or in Lua path.

------------------
---- MONITORS ----
------------------
require("conf.monitors")

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------
require("conf.env")

---------------
---- INPUT ----
---------------
require("conf.input")

-------------------
---- AUTOSTART ----
-------------------
require("conf.autostart")

-----------------------
---- LOOK AND FEEL ----
-----------------------
require("conf.general") -- gaps, borders, dwindle, master, misc top-level
require("conf.decorations")
require("conf.animations")

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------
require("conf.workspaces")

---------------
---- MISC ----
---------------
-- (some misc already in general.lua)

----------------
---- GESTURES --
----------------
require("conf.gestures")

----------------
---- PLUGINS ---
----------------
require("conf.plugins")

---------------------
---- KEYBINDINGS ----
---------------------
require("conf.keybinds")

--------------------------------
---- WINDOW / LAYER RULES ----
--------------------------------
require("conf.windowrules")
require("conf.layerrules")

-- -----------------------------------------------------
-- Final direct items from original hyprland.conf
-- -----------------------------------------------------

-- exec-once already handled in autostart.lua via hl.on("hyprland.start"...

-- Some direct lines that were at the very end of hyprland.conf
-- hl.exec_cmd('gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"') -- for GTK4 apps
-- hl.exec_cmd(SCRIPTS .. "/konsole_wal.sh")
-- hl.exec_cmd("kded5")
-- hl.exec_cmd("/usr/lib/org_kde_powerdevil")

-- Mouse resize bind that was outside any sourced file
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- HyprEmoji (external)
-- If you still use it, source its config or convert separately.
-- source = ~/.config/hypremoji/hypremoji.conf

-- Optional: remove the autogenerated warning if you had one
-- hl.config({ autogenerated = false })

print("[hypr] hyprland.lua loaded successfully (Lua config active)")
