#  _   _                  _                 _
# | | | |_   _ _ __  _ __| | __ _ _ __   __| |
# | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` |
# |  _  | |_| | |_) | |  | | (_| | | | | (_| |
# |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
#        |___/|_|
# -----------------------------------------------------

$SCRIPTS = ~/.config/hypr/scripts

# -----------------------------------------------------
# Monitor
# -----------------------------------------------------
source = ~/.config/hypr/conf/monitor.conf

# -----------------------------------------------------
# Environment
# -----------------------------------------------------
source = ~/.config/hypr/conf/environment.conf

# -----------------------------------------------------
# Keyboard
# -----------------------------------------------------
source = ~/.config/hypr/conf/keyboard.conf

# -----------------------------------------------------
# Load color files early (important for plugins and window rules)
# -----------------------------------------------------
source = ~/.config/hypr/colors/colors.conf          # static fallback (gruvbox etc.)
source = ~/.cache/wal/colors-hyprland.conf
source = ~/.config/hypr/colors/custom/matugen.conf  # Matugen dynamic colors

# -----------------------------------------------------
# Autostart
# -----------------------------------------------------
source = ~/.config/hypr/conf/autostart.conf

# -----------------------------------------------------
# Load configuration files
# -----------------------------------------------------
source = ~/.config/hypr/conf/window.conf
source = ~/.config/hypr/conf/decorations.conf
source = ~/.config/hypr/conf/layout.conf
source = ~/.config/hypr/conf/keybinding.conf
source = ~/.config/hypr/conf/windowrule.conf
source = ~/.config/hypr/conf/misc.conf
source = ~/.config/hypr/conf/workspaces.conf
source = ~/.config/hypr/conf/plugins.conf
source = ~/.config/hypr/conf/gestures.conf
source = ~/.config/hypr/conf/animations.conf
# source = ~/.config/hypr/hyprpaper.conf   # disabled - using Waypaper + awww instead

env = TERMINAL,$SCRIPTS/terminal.sh
env = BROWSER,$SCRIPTS/browser.sh
env = FILEMANAGER,$SCRIPTS/filemanagers.sh

# -----------------------------------------------------
# Settings
# -----------------------------------------------------
# source = ~/.config/hypr/conf/settings.conf
exec-once = systemctl --user start hyprpolkitagent

# source = ~/.cache/wal/colors-hyprland.conf

# -----------------------------------------------------
# Restore Wallpaper on Login
# -----------------------------------------------------
exec-once = $SCRIPTS/waybar_kill.sh
exec-once = $SCRIPTS/launch.sh
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
exec = $SCRIPTS/konsole_wal.sh
exec-once = kded5
exec-once = /usr/lib/org_kde_powerdevil
bindm = SUPER, mouse:273, resizewindow

# HyprEmoji config
source = ~/.config/hypremoji/hypremoji.conf

# export XDG_CURRENT_DESKTOP=Hyprland
# env = GTK_THEME,Gruvbox-Material-Dark

