-- Generated by NothingLess on 2026-06-07 at 16:58:06. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "1920x1080@60",
    position = "900x59",
    scale = 1.2
})

hl.monitor({
    output = "DVI-I-1",
    mode = "1920x1080@60",
    position = "0x59",
    scale = 1.2,
    transform = 1
})

hl.monitor({
    output = "DVI-I-2",
    mode = "1920x1080@60",
    position = "4102x0",
    scale = 1.0
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60",
    position = "2501x59",
    scale = 1.2
})

