-- Matugen integration for Neovim
-- Uses mini.base16 + the file generated by matugen/templates/neovim-mini.lua
--
-- Live reload: matugen sends SIGUSR1 after writing the new theme file.
-- The Signal autocmd below will pick it up in all running Neovim instances.

return {
  {
    "echasnovski/mini.base16",
    lazy = false,
    priority = 1000, -- load very early so colors are set before UI plugins
    config = function()
      local function load_matugen()
        local path = vim.fn.stdpath("config") .. "/lua/matugen-theme.lua"
        if vim.fn.filereadable(path) == 1 then
          dofile(path)
        else
          -- First run / no wallpaper yet → gentle fallback
          -- You can change this to any colorscheme you have installed.
          pcall(vim.cmd.colorscheme, "tokyonight-night")
        end
      end

      load_matugen()

      -- Live reload when matugen runs (pkill -SIGUSR1 nvim from the template hook)
      vim.api.nvim_create_autocmd("Signal", {
        pattern = "SIGUSR1",
        callback = function()
          load_matugen()

          -- Many UI plugins cache highlights; a gentle redraw helps
          vim.schedule(function()
            pcall(vim.cmd.redrawstatus)
            pcall(vim.cmd.redrawtabline)
          end)
        end,
      })
    end,
  },
}
