# -----------------------------------------------------
# Autostart
# ----------------------------------------------------- 

$SCRIPTS = ~/.config/hypr/scripts

# Hyprpm
exec-once = hyprpm reload

# Privilege escalation
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Using hypridle to start hyprlock
exec-once = hypridle & waybar

# For images too (recommended)
exec-once = wl-paste --type image --watch cliphist store

# Start autostart cleanup
exec-once = $SCRIPTS/cleanup.sh

exec-once = $SCRIPTS/reload_wallpaper.sh

# Symlinks for scripts
exec-once = waypaper-engine daemon
exec-once = killall waybar && hyprpaper && waypaper --restore

# Load Dunst Notification Manager
exec-once = dunst

# hyprctl.sh
exec = ~/.config/hypr/hpyrctl/hyprctl.sh

# Start Waypaper
exec-once = ~/.local/bin/waypaper --r

# Cursor
exec-once = hyprctl setcursor Bibatta-Modern-Classic-Gruvbox 24

# Workspaces
exec-once = $SCRIPTS/monitor-workspaces.sh

# load all the plugins you installed
exec-once = hyprctl plugin load "$HYPR_PLUGIN_DIR/lib/libhyprexpo.so"

#exec-once = hyprpm add hyprexpo
# Auto-mount removable storage
exec-once = udiskie

# Launch
# exec-once =  $SCRIPTS/launch.sh

# Idling
exec-once = hypridle

# Alt + Tab
exec-once = snappy-switcher --daemon


# Notification center
# exec-once = swaync

# Start nwg-dock-hyprland
# exec-once = nwg-dock-hyprland
# exec-once = nwg-dock-hyprland -o DVI-I-1

# KDE Connect
# exec-once = kde-connect
# exec-once = sleep 2s && kdeconnect-indicator

# Load GTK settings
exec-once = $SCRIPTS/gtk.sh

# Dolphin Fix.sh
# exec-once = ~/scripts/dolphin_fix.sh

# Start ewww daemon
# exec-once = $SCRIPTS/ags.sh
# exec-once = ags

# For text only
# exec-once = wl-paste --type text --watch cliphist store


# Start Polkit
# exec-once=/usr/lib/polkit-gnome/polkit-kde-agent

