# -----------------------------------------------------
# Autostart
# ----------------------------------------------------- 

# Start Polkit
exec-once=/usr/lib/polkit-gnome/polkit-kde-agent

# Using hypridle to start hyprlock
exec-once = hypridle & waybar

# Load cliphist history
exec-once = wl-paste --watch cliphist store

# Start ewww daemon
exec-once = ~/scripts/ags.sh
exec-once = ags

# Start autostart cleanup
exec-once = ~/scripts/cleanup.sh

# Start nwg-dock-hyprland
exec-once = nwg-dock-hyprland
exec-once = ~/scripts/reload_wallpaper.sh

# Symlinks for scripts
exec-once = waypaper-engine daemon
exec-once = killall waybar && hyprpaper && waypaper --restore

# Load Dunst Notification Manager
exec-once = dunst

# Load GTK settings
exec-once = ~/scripts/gtk.sh

# hyprctl.sh
exec = ~/.config/hypr/hpyrctl/hyprctl.sh

# Start Waypaper
# exec-once = ~/.local/bin/waypaper --r

# Dolphin Fix.sh
exec-once = ~/scripts/dolphin_fix.sh

# KDE Connect
# exec-once = kde-connect
# exec-once = sleep 2s && kdeconnect-indicator
