# -----------------------------------------------------
# Autostart
# ----------------------------------------------------- 

# Start Polkit
exec-once=/usr/lib/polkit-gnome/polkit-kde-agent

exec-once = hyprpm update

# Privilege escalation
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Using hypridle to start hyprlock
exec-once = hypridle & waybar

# For text only
exec-once = wl-paste --type text --watch cliphist store

# For images too (recommended)
exec-once = wl-paste --type image --watch cliphist store

# Start ewww daemon
exec-once = ~/scripts/ags.sh
exec-once = ags

# Start autostart cleanup
exec-once = ~/scripts/cleanup.sh

exec-once = ~/scripts/reload_wallpaper.sh

# Symlinks for scripts
exec-once = waypaper-engine daemon
exec-once = killall waybar && hyprpaper && waypaper --restore

# Load Dunst Notification Manager
exec-once = dunst

# hyprctl.sh
exec = ~/.config/hypr/hpyrctl/hyprctl.sh

# Start Waypaper
exec-once = ~/.local/bin/waypaper --r

# Dolphin Fix.sh
exec-once = ~/scripts/dolphin_fix.sh

# Cursor
exec-once = hyprctl setcursor Bibatta-Modern-Classic-Gruvbox 24

# Workspaces
exec-once = ~/.config/hypr/scripts/monitor-workspaces.sh

# load all the plugins you installed
exec-once = hyprctl plugin load "$HYPR_PLUGIN_DIR/lib/libhyprexpo.so"



#exec-once = hyprpm add hyprexpo
# Auto-mount removable storage
exec-once = udiskie

# Idling
#exec-once = hypridle

# Notification center
#exec-once = swaync

# Start nwg-dock-hyprland
# exec-once = nwg-dock-hyprland
# exec-once = nwg-dock-hyprland -o DVI-I-1

# KDE Connect
# exec-once = kde-connect
# exec-once = sleep 2s && kdeconnect-indicator

# Load GTK settings
# exec-once = ~/scripts/gtk.sh

