# -- Input device stuff  -- #

input {
    kb_layout = us

    follow_mouse = 1

    touchpad {
        natural_scroll = true
    }

    sensitivity = 0

    repeat_delay = 300   # ms before repeating starts
    repeat_rate  = 30   # repeats per second

    numlock_by_default = true     # ← add this
    # kb_options = numpad:mac     # optional, helps some external numpads
}

