# ----------------------------------------------------- 
# Misc settings
# ----------------------------------------------------- 

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    initial_workspace_tracking = 1
    animate_mouse_windowdragging = false
 
    # Variable frame rate
    #vfr = true

    # Enable window swallowing 
    enable_swallow = false
    swallow_regex = ^(Alacritty|kitty|footclient|brave-browser)$
}

# Don't inform about updates 
ecosystem:no_update_news = true

# File association in dolphin.
env = XDG_MENU_PREFIX,plasma-

# source = ~.config/hypr/colors/matugen.conf
input:sensitivity = 0.1
force_default_wallpaper ='~/pictures/wallpapers/alley_gruv.jpg:'
mouse_move_enables_dpms = true
force_zero_scaling = true
no_donation_nag = true

# snap:enabled = 
# snap:monitor_ga
# snap:window_gap

# Load the plugin
plugin = /home/.config/hypr/hypr-hot-edge/build/hypr-hot-edge.so

# Configure edge slots (edge1 through edge8)
plugin {
   hot-edge {
        # Each slot can be any edge on any monitor
        # side = left/right/top/bottom
        # target_monitor = "*" for all, or specific name like "DP-1"

        edge1 {
            enabled = 1
            side = right
            trigger_width = 15        # pixels from edge to trigger zone
            dwell_time = 150          # ms delay before triggering (0 = instant)
            special_workspace = hotedge-right-mon1
            target_monitor = HDMI-A-1
        }

        edge2 {
            enabled = 1
            side = right
            trigger_width = 15
            dwell_time = 150
            special_workspace = hotedge-right-mon2
            target_monitor = DP-3
        }

        edge3 {
            enabled = 1
            side = bottom
            trigger_width = 15
            dwell_time = 150
            special_workspace = hotedge-bottom-mon1
            target_monitor = HDMI-A-1
        }

        edge4 {
            enabled = 1
            side = bottom
            trigger_width = 15
            dwell_time = 150
            special_workspace = hotedge-bottom-mon2
            target_monitor = DP-3
        }

        # edge5 through edge8 available for more configurations
    }
}

dwindle {
    preserve_split = true   # important!
    # force_split = 0       # optional
}
