#!/usr/bin/env bash
# grub.sh — install & set Tartarus GRUB theme
set -euo pipefail
IFS=$'\n\t'

# ------------------------------------------------------------
# Resolve repo root from lib/scripts/
# ------------------------------------------------------------
HYPR_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# Load helpers
if [[ ! -f "$HYPR_DIR/lib/common.sh" ]]; then
  echo "[ERROR] Missing: $HYPR_DIR/lib/common.sh"; exit 1
fi
if [[ ! -f "$HYPR_DIR/lib/state.sh" ]]; then
  echo "[ERROR] Missing: $HYPR_DIR/lib/state.sh"; exit 1
fi
# shellcheck source=/dev/null
source "$HYPR_DIR/lib/common.sh"
# shellcheck source=/dev/null
source "$HYPR_DIR/lib/state.sh"

display_header "GRUB Theme (Tartarus)"

# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------
ASSET_ROOT="$HYPR_DIR/assets/tartarus"
THEMES_DIR="/usr/share/grub/themes"
THEME_NAME="tartarus"
THEME_DST="$THEMES_DIR/$THEME_NAME"
GRUB_DEFAULT="/etc/default/grub"
GRUB_THEME_FILE="$THEME_DST/theme.txt"   # common name for Tartarus theme file

# Basic sanity
if [[ ! -d "$ASSET_ROOT" ]]; then
  log_error "Theme assets not found at: $ASSET_ROOT"
  exit 1
fi

# Some repos ship either:
#   assets/tartarus/<theme files here>
# or
#   assets/tartarus/tartarus/<theme files here>
if [[ -d "$ASSET_ROOT/$THEME_NAME" ]]; then
  SRC_DIR="$ASSET_ROOT/$THEME_NAME"
else
  SRC_DIR="$ASSET_ROOT"
fi

# ------------------------------------------------------------
# Install theme into /usr/share/grub/themes/tartarus
# ------------------------------------------------------------
log_status "Installing theme into: $THEME_DST"
sudo install -d -m 0755 "$THEMES_DIR"
if [[ -d "$THEME_DST" ]]; then
  sudo rm -rf "$THEME_DST"
fi
sudo install -d -m 0755 "$THEME_DST"
sudo cp -a "$SRC_DIR"/. "$THEME_DST/"

# If your assets directory also contains a prebuilt /etc/default/grub file,
# we will use that below; otherwise we will just set GRUB_THEME.
ASSET_GRUB_FILE="$ASSET_ROOT/grub"

# ------------------------------------------------------------
# Backup current /etc/default/grub
# ------------------------------------------------------------
if [[ -f "$GRUB_DEFAULT" ]]; then
  TS="$(date +%Y%m%d_%H%M%S)"
  sudo cp -a "$GRUB_DEFAULT" "$GRUB_DEFAULT.bak.$TS"
  log_status "Backed up $GRUB_DEFAULT to $GRUB_DEFAULT.bak.$TS"
else
  log_status "No existing $GRUB_DEFAULT found; creating new."
  echo -e '# Generated by hyprgruv installer\nGRUB_DEFAULT=0\nGRUB_TIMEOUT=5' | sudo tee "$GRUB_DEFAULT" >/dev/null
fi

# ------------------------------------------------------------
# Configure GRUB_THEME line
# ------------------------------------------------------------
if [[ -f "$ASSET_GRUB_FILE" ]]; then
  # Use your provided /etc/default/grub (safer to merge/replace the GRUB_THEME line afterwards)
  log_status "Merging GRUB_THEME from asset file"
  # Copy the asset file aside and prefer its GRUB_THEME line
  TMP_ASSET="$(mktemp)"
  cp -a "$ASSET_GRUB_FILE" "$TMP_ASSET"

  # Extract GRUB_THEME from asset (if present)
  ASSET_THEME_LINE="$(grep -E '^GRUB_THEME=' "$TMP_ASSET" || true)"
  if [[ -n "$ASSET_THEME_LINE" ]]; then
    # Ensure path points to installed theme location
    ASSET_THEME_LINE="GRUB_THEME=\"$GRUB_THEME_FILE\""
    # Replace or append in /etc/default/grub
    if grep -qE '^GRUB_THEME=' "$GRUB_DEFAULT"; then
      sudo sed -i 's|^GRUB_THEME=.*$|'"$ASSET_THEME_LINE"'|' "$GRUB_DEFAULT"
    else
      echo "$ASSET_THEME_LINE" | sudo tee -a "$GRUB_DEFAULT" >/dev/null
    fi
  else
    # Asset file had no GRUB_THEME; just set it ourselves
    if grep -qE '^GRUB_THEME=' "$GRUB_DEFAULT"; then
      sudo sed -i 's|^GRUB_THEME=.*$|GRUB_THEME="'"$GRUB_THEME_FILE"'"|' "$GRUB_DEFAULT"
    else
      echo 'GRUB_THEME="'"$GRUB_THEME_FILE"'"' | sudo tee -a "$GRUB_DEFAULT" >/dev/null
    fi
  fi
  rm -f "$TMP_ASSET"
else
  # No asset grub file — set/replace GRUB_THEME directly
  log_status "Setting GRUB_THEME in $GRUB_DEFAULT"
  if grep -qE '^GRUB_THEME=' "$GRUB_DEFAULT"; then
    sudo sed -i 's|^GRUB_THEME=.*$|GRUB_THEME="'"$GRUB_THEME_FILE"'"|' "$GRUB_DEFAULT"
  else
    echo 'GRUB_THEME="'"$GRUB_THEME_FILE"'"' | sudo tee -a "$GRUB_DEFAULT" >/dev/null
  fi
fi

# ------------------------------------------------------------
# Regenerate GRUB config
# ------------------------------------------------------------
log_status "Rebuilding GRUB configuration"
if [[ -d /sys/firmware/efi ]]; then
  # Typical for UEFI systems
  sudo grub-mkconfig -o /boot/grub/grub.cfg
else
  # Legacy BIOS fallback (still same default path on Arch)
  sudo grub-mkconfig -o /boot/grub/grub.cfg
fi

log_success "GRUB theme installed and configured"
