#!/usr/bin/env bash
# zram.sh — optional guided zram-generator setup
set -euo pipefail
IFS=$'\n\t'

HYPR_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
[[ -f "$HYPR_DIR/lib/common.sh" ]] || {
    echo "[ERROR] Missing: $HYPR_DIR/lib/common.sh"
    exit 1
}
[[ -f "$HYPR_DIR/lib/state.sh" ]] || {
    echo "[ERROR] Missing: $HYPR_DIR/lib/state.sh"
    exit 1
}
# shellcheck source=/dev/null
source "$HYPR_DIR/lib/common.sh"
# shellcheck source=/dev/null
source "$HYPR_DIR/lib/state.sh"

ensure_cmd() {
    local c="$1" install_msg="$2" pkg="$3"
    if ! command -v "$c" >/dev/null 2>&1; then
        log_status "$install_msg"
        if command -v yay >/dev/null 2>&1; then
            yay -S --needed --noconfirm "$pkg"
        else
            sudo pacman -S --needed --noconfirm "$pkg"
        fi
    fi
}

ensure_cmd gum "Installing gum…" gum

source "$HOME/.config/hypr/scripts/header.sh" 2>/dev/null || true
source "$HOME/.config/hypr/scripts/colors.sh" 2>/dev/null || true
gum_apply_matugen_theme

toilet -f graffiti ZRam | lsd-print

ZRAM_CONF="/etc/systemd/zram-generator.conf"

echo ""
echo "Zram compresses a slice of RAM and uses it as swap."
echo "It can reduce memory pressure without wearing an SSD."
echo "This wizard configures systemd's zram-generator."
sleep 0.5

if swapon --show 2>/dev/null | grep -q zram; then
    log_status "Zram swap is already active:"
    swapon --show | grep zram || true
    echo ""
    if ! gum confirm "Reconfigure zram anyway?"; then
        log_status "Zram setup skipped."
        exit 0
    fi
fi

if [[ -f "$ZRAM_CONF" ]]; then
    log_status "Existing config: $ZRAM_CONF"
    echo ""
    sudo cat "$ZRAM_CONF" 2>/dev/null || true
    echo ""
fi

log_status "Step 1/4 — Install zram-generator"
if ! pacman -Qq zram-generator &>/dev/null; then
    if command -v yay >/dev/null 2>&1; then
        yay -S --needed --noconfirm zram-generator
    else
        sudo pacman -S --needed --noconfirm zram-generator
    fi
    log_success "zram-generator installed"
else
    log_success "zram-generator already installed"
fi

echo ""
log_status "Step 2/4 — Choose zram size"
size_choice=$(gum choose \
    "Half of RAM (recommended)" \
    "Quarter of RAM (conservative)" \
    "min(ram/2, 4096) — cap at 4 GiB" \
    "Cancel" \
    --header "Zram size:")

case "$size_choice" in
"Half of RAM (recommended)")
    ZRAM_SIZE="ram / 2"
    ;;
"Quarter of RAM (conservative)")
    ZRAM_SIZE="ram / 4"
    ;;
"min(ram/2, 4096) — cap at 4 GiB")
    ZRAM_SIZE="min(ram / 2, 4096)"
    ;;
*)
    log_status "Zram setup canceled."
    exit 0
    ;;
esac

algo_choice=$(gum choose "zstd (recommended)" "lzo" "lz4" "Cancel" --header "Compression:")
case "$algo_choice" in
"zstd (recommended)") COMPRESSION="zstd" ;;
lzo) COMPRESSION="lzo" ;;
lz4) COMPRESSION="lz4" ;;
*)
    log_status "Zram setup canceled."
    exit 0
    ;;
esac

log_status "Step 3/4 — Write $ZRAM_CONF"
if [[ -f "$ZRAM_CONF" ]]; then
    sudo cp -a "$ZRAM_CONF" "${ZRAM_CONF}.bak.$(date +%Y%m%d_%H%M%S)"
fi

sudo tee "$ZRAM_CONF" >/dev/null <<EOF
# Generated by hyprgruv zram.sh
[zram0]
zram-size = ${ZRAM_SIZE}
compression-algorithm = ${COMPRESSION}
swap-priority = 100
EOF

log_success "Config written"

log_status "Step 4/4 — Reload systemd and activate zram"
sudo systemctl daemon-reload

if systemctl list-units --type=swap --all 2>/dev/null | grep -q 'dev-zram0.swap'; then
    sudo systemctl restart dev-zram0.swap 2>/dev/null || true
elif systemctl list-units --type=swap --all 2>/dev/null | grep -q 'zram'; then
    sudo systemctl restart "$(systemctl list-units --type=swap --all --no-legend | awk '/zram/ {print $1; exit}')" 2>/dev/null || true
fi

sleep 1
if swapon --show 2>/dev/null | grep -q zram; then
    log_success "Zram is active"
    swapon --show | grep zram || true
else
    log_warning "Zram not active yet — reboot to apply: sudo reboot"
fi

echo ""
log_status "Verify anytime with: swapon --show"
log_success "Zram setup complete"

