--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kirk/wallpaper/Lady.png"

-- Special
background="#1e1d1c"
foreground="#c6c6c6"
cursor="#c6c6c6"

-- Colors
color0="#1e1d1c"
color1="#928B78"
color2="#A0967F"
color3="#9F9B86"
color4="#B3AC91"
color5="#C4BB9D"
color6="#BAC0A6"
color7="#c6c6c6"
color8="#767660"
color9="#928B78"
color10="#A0967F"
color11="#9F9B86"
color12="#B3AC91"
color13="#C4BB9D"
color14="#BAC0A6"
color15="#c6c6c6"
