foreground         #c1c3c5
background         #0a1018
background_opacity 1.0
cursor             #c1c3c5

active_tab_foreground     #0a1018
active_tab_background     #c1c3c5
inactive_tab_foreground   #c1c3c5
inactive_tab_background   #0a1018

active_border_color   #c1c3c5
inactive_border_color #0a1018
bell_border_color     #837C78

color0       #0a1018
color8       #59626d
color1       #837C78
color9       #837C78
color2       #7C837E
color10      #7C837E
color3       #89827D
color11      #89827D
color4       #968F89
color12      #968F89
color5       #A39C95
color13      #A39C95
color6       #AAA39C
color14      #AAA39C
color7       #c1c3c5
color15      #c1c3c5
