[colors.primary]
background = '#101119'
foreground = '#c3c3c5'

[colors.cursor]
text = '#c3c3c5'
cursor = '#c3c3c5'

[colors.normal]
black = '#101119'
red = '#5E6A83'
green = '#71748A'
yellow = '#887A8E'
blue = '#7B849C'
magenta = '#9793AA'
cyan = '#ACAECF'
white = '#c3c3c5'

[colors.bright]
black = '#5b5f70'
red = '#5E6A83'
green = '#71748A'
yellow = '#887A8E'
blue = '#7B849C'
magenta = '#9793AA'
cyan = '#ACAECF'
white = '#c3c3c5'
