$foreground = rgb(c2c4c5)
$background = rgb(0b1419)
$backgroundRgb = 11,20,25
$backgroundAlpha = rgba(0b1419db)
$wallpaper = rgb(home/kirk/wallpaper/Patterns.png)

$color0 = rgb(0b1419)
$color1 = rgb(808071)
$color1Alpha = rgba(808071db)
$color2 = rgb(898979)
$color2Alpha = rgba(808071db)
$color3 = rgb(A7A794)
$color4 = rgb(C1BEA9)
$color5 = rgb(CECCB5)
$color6 = rgb(DDDBC4)
$color7 = rgb(c2c4c5)
$color8 = rgb(5a676e)
$color9 = rgb(808071)
$color10 = rgb(898979)
$color11 = rgb(A7A794)
$color12 = rgb(C1BEA9)
$color13 = rgb(CECCB5)
$color14 = rgb(DDDBC4)
$color15 = rgb(c2c4c5)

