[colors]
background = '#1113138e'
black = '#111313'
blue = '#656158'
cursor = '#c3c4c4'
cyan = '#6C7268'
foreground = '#c3c4c4'
green = '#B15A44'
magenta = '#788873'
red = '#ABA06F'
tabs = '#c3c4c4'
tabs-active = '#848881'
white = '#c3c4c4'
yellow = '#c3c4c4'
dim-black = '#1113138e'
dim-blue = '#6561588e'
dim-cyan = '#6C72688e'
dim-foreground = '#c3c4c48e'
dim-green = '#B15A448e'
dim-magenta = '#7888738e'
dim-red = '#ABA06F8e'
dim-white = '#8488818e'
dim-yellow = '#c3c4c48e'
light-black = '#656158'
light-blue = '#6C7268'
light-cyan = '#B15A44'
light-foreground = '#788873'
light-green = '#ABA06F'
light-magenta = '#848881'
light-red = '#c3c4c4'
light-white = '#656158'
light-yellow = '#6C7268'
