$foreground = rgb(c4c1c1)
$background = rgb(160909)
$backgroundRgb = 22,9,9
$backgroundAlpha = rgba(160909db)
$wallpaper = rgb(home/kirk/Pictures/Wallpapers/bw_wallhaven-1qx9eg.png)

$color0 = rgb(160909)
$color1 = rgb(4D4D4D)
$color1Alpha = rgba(4D4D4Ddb)
$color2 = rgb(605F60)
$color2Alpha = rgba(4D4D4Ddb)
$color3 = rgb(6E6E6E)
$color4 = rgb(8E8E8E)
$color5 = rgb(A09FA0)
$color6 = rgb(AEAEAE)
$color7 = rgb(c4c1c1)
$color8 = rgb(6c5959)
$color9 = rgb(4D4D4D)
$color10 = rgb(605F60)
$color11 = rgb(6E6E6E)
$color12 = rgb(8E8E8E)
$color13 = rgb(A09FA0)
$color14 = rgb(AEAEAE)
$color15 = rgb(c4c1c1)

