[colors]
ansi = [
    "#121212",
    "#71342A",
    "#8F3A2B",
    "#AD3D29",
    "#CE3F27",
    "#964232",
    "#B0422E",
    "#c3c3c3",
]
background = "#121212"
brights = [
    "#6e5959",
    "#71342A",
    "#8F3A2B",
    "#AD3D29",
    "#CE3F27",
    "#964232",
    "#B0422E",
    "#c3c3c3",
]
cursor_bg = "#c3c3c3"
cursor_border = "#c3c3c3"
cursor_fg = "#121212"
foreground = "#c3c3c3"
selection_bg = "#CE3F27"
selection_fg = "#121212"

