--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kirk/Pictures/dark-minimalism-fish-red-wallpaper-preview.jpg"

-- Special
background="#121212"
foreground="#c3c3c3"
cursor="#c3c3c3"

-- Colors
color0="#121212"
color1="#71342A"
color2="#8F3A2B"
color3="#AD3D29"
color4="#CE3F27"
color5="#964232"
color6="#B0422E"
color7="#c3c3c3"
color8="#6e5959"
color9="#71342A"
color10="#8F3A2B"
color11="#AD3D29"
color12="#CE3F27"
color13="#964232"
color14="#B0422E"
color15="#c3c3c3"
