[colors.primary]
background = '#101011'
foreground = '#c3c3c3'

[colors.cursor]
text = '#c3c3c3'
cursor = '#c3c3c3'

[colors.normal]
black = '#101011'
red = '#689E6B'
green = '#DB981D'
yellow = '#CA992E'
blue = '#D9A124'
magenta = '#938B75'
cyan = '#438489'
white = '#c3c3c3'

[colors.bright]
black = '#59596d'
red = '#689E6B'
green = '#DB981D'
yellow = '#CA992E'
blue = '#D9A124'
magenta = '#938B75'
cyan = '#438489'
white = '#c3c3c3'
