[colors]
ansi = [
    "#1a0b0b",
    "#384367",
    "#4A4F50",
    "#62696C",
    "#6A6F8E",
    "#817D9A",
    "#78868C",
    "#c5c2c2",
]
background = "#1a0b0b"
brights = [
    "#6f5a5a",
    "#384367",
    "#4A4F50",
    "#62696C",
    "#6A6F8E",
    "#817D9A",
    "#78868C",
    "#c5c2c2",
]
cursor_bg = "#c5c2c2"
cursor_border = "#c5c2c2"
cursor_fg = "#1a0b0b"
foreground = "#c5c2c2"
selection_bg = "#6A6F8E"
selection_fg = "#1a0b0b"

