[colors]
background = '#0b14198e'
black = '#0b1419'
blue = '#808071'
cursor = '#c2c4c5'
cyan = '#898979'
foreground = '#c2c4c5'
green = '#A7A794'
magenta = '#C1BEA9'
red = '#CECCB5'
tabs = '#c2c4c5'
tabs-active = '#DDDBC4'
white = '#c2c4c5'
yellow = '#c2c4c5'
dim-black = '#0b14198e'
dim-blue = '#8080718e'
dim-cyan = '#8989798e'
dim-foreground = '#c2c4c58e'
dim-green = '#A7A7948e'
dim-magenta = '#C1BEA98e'
dim-red = '#CECCB58e'
dim-white = '#DDDBC48e'
dim-yellow = '#c2c4c58e'
light-black = '#808071'
light-blue = '#898979'
light-cyan = '#A7A794'
light-foreground = '#C1BEA9'
light-green = '#CECCB5'
light-magenta = '#DDDBC4'
light-red = '#c2c4c5'
light-white = '#808071'
light-yellow = '#898979'
