foreground   #f4f0da
background   #101212
cursor       #f4f0da

color0       #101212
color8       #aaa898
color1       #3F8288
color9       #3F8288
color2       #478789
color10      #478789
color3       #739C8F
color11      #739C8F
color4       #83A598
color12      #83A598
color5       #9FAB96
color13      #9FAB96
color6       #CBD1A8
color14      #CBD1A8
color7       #f4f0da
color15      #f4f0da
