[colors]
background = '#1010118e'
black = '#101011'
blue = '#689E6B'
cursor = '#c3c3c3'
cyan = '#DB981D'
foreground = '#c3c3c3'
green = '#CA992E'
magenta = '#D9A124'
red = '#938B75'
tabs = '#c3c3c3'
tabs-active = '#438489'
white = '#c3c3c3'
yellow = '#c3c3c3'
dim-black = '#1010118e'
dim-blue = '#689E6B8e'
dim-cyan = '#DB981D8e'
dim-foreground = '#c3c3c38e'
dim-green = '#CA992E8e'
dim-magenta = '#D9A1248e'
dim-red = '#938B758e'
dim-white = '#4384898e'
dim-yellow = '#c3c3c38e'
light-black = '#689E6B'
light-blue = '#DB981D'
light-cyan = '#CA992E'
light-foreground = '#D9A124'
light-green = '#938B75'
light-magenta = '#438489'
light-red = '#c3c3c3'
light-white = '#689E6B'
light-yellow = '#DB981D'
