# Shell variables
# Generated by 'wal'
wallpaper="/home/kirk/Pictures/aroace-plain-wide.png"

# Special
background='#171818'
foreground='#c5c5c5'
cursor='#c5c5c5'

# Colors
color0='#171818'
color1='#D75D0E'
color2='#C25711'
color3='#D66410'
color4='#D7921F'
color5='#D79921'
color6='#DBA436'
color7='#c5c5c5'
color8='#725d5d'
color9='#D75D0E'
color10='#C25711'
color11='#D66410'
color12='#D7921F'
color13='#D79921'
color14='#DBA436'
color15='#c5c5c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
