[colors.primary]
background = '#101213'
foreground = '#c3c3c4'

[colors.cursor]
text = '#c3c3c4'
cursor = '#c3c3c4'

[colors.normal]
black = '#101213'
red = '#D58A75'
green = '#749190'
yellow = '#7B9E95'
blue = '#879893'
magenta = '#8CA799'
cyan = '#AEA098'
white = '#c3c3c4'

[colors.bright]
black = '#59636e'
red = '#D58A75'
green = '#749190'
yellow = '#7B9E95'
blue = '#879893'
magenta = '#8CA799'
cyan = '#AEA098'
white = '#c3c3c4'
