# Shell variables
# Generated by 'wal'
wallpaper='/home/kirk/wallpaper/gruv_waves.webp'

# Special
background='#0f1010'
foreground='#cacabe'
cursor='#cacabe'

# Colors
color0='#0f1010'
color1='#777B72'
color2='#948B77'
color3='#8FC17B'
color4='#3E8285'
color5='#458588'
color6='#749D91'
color7='#cacabe'
color8='#8d8d85'
color9='#777B72'
color10='#948B77'
color11='#8FC17B'
color12='#3E8285'
color13='#458588'
color14='#749D91'
color15='#cacabe'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
