$foreground = rgb(c6c6c8)
$background = rgb(1b1e25)
$backgroundRgb = 27,30,37
$backgroundAlpha = rgba(1b1e25db)
$wallpaper = rgb(home/kirk/wallpaper/at_the_coffeshop.png)

$color0 = rgb(1b1e25)
$color1 = rgb(637A86)
$color1Alpha = rgba(637A86db)
$color2 = rgb(6E8A93)
$color2Alpha = rgba(637A86db)
$color3 = rgb(7A9CA2)
$color4 = rgb(7EA2A6)
$color5 = rgb(8FBBBB)
$color6 = rgb(92C0BE)
$color7 = rgb(c6c6c8)
$color8 = rgb(626878)
$color9 = rgb(637A86)
$color10 = rgb(6E8A93)
$color11 = rgb(7A9CA2)
$color12 = rgb(7EA2A6)
$color13 = rgb(8FBBBB)
$color14 = rgb(92C0BE)
$color15 = rgb(c6c6c8)

