--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kirk/wallpaper/battle.png"

-- Special
background="#101213"
foreground="#e0d6c8"
cursor="#e0d6c8"

-- Colors
color0="#101213"
color1="#C99727"
color2="#958675"
color3="#498688"
color4="#A89984"
color5="#8AA192"
color6="#BCAD92"
color7="#e0d6c8"
color8="#9c958c"
color9="#C99727"
color10="#958675"
color11="#498688"
color12="#A89984"
color13="#8AA192"
color14="#BCAD92"
color15="#e0d6c8"
