# Shell variables
# Generated by 'wal'
wallpaper="/home/kirk/Pictures/Wallpapers/bw_wallhaven-1qx9eg.png"

# Special
background='#160909'
foreground='#c4c1c1'
cursor='#c4c1c1'

# Colors
color0='#160909'
color1='#4D4D4D'
color2='#605F60'
color3='#6E6E6E'
color4='#8E8E8E'
color5='#A09FA0'
color6='#AEAEAE'
color7='#c4c1c1'
color8='#6c5959'
color9='#4D4D4D'
color10='#605F60'
color11='#6E6E6E'
color12='#8E8E8E'
color13='#A09FA0'
color14='#AEAEAE'
color15='#c4c1c1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
