foreground         #c3c3c3
background         #101011
background_opacity 1.0
cursor             #c3c3c3

active_tab_foreground     #101011
active_tab_background     #c3c3c3
inactive_tab_foreground   #c3c3c3
inactive_tab_background   #101011

active_border_color   #c3c3c3
inactive_border_color #101011
bell_border_color     #689E6B

color0       #101011
color8       #59596d
color1       #689E6B
color9       #689E6B
color2       #DB981D
color10      #DB981D
color3       #CA992E
color11      #CA992E
color4       #D9A124
color12      #D9A124
color5       #938B75
color13      #938B75
color6       #438489
color14      #438489
color7       #c3c3c3
color15      #c3c3c3
