--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kirk/wallpaper/gruv_waves.webp"

-- Special
background="#0f1010"
foreground="#cacabe"
cursor="#cacabe"

-- Colors
color0="#0f1010"
color1="#777B72"
color2="#948B77"
color3="#8FC17B"
color4="#3E8285"
color5="#458588"
color6="#749D91"
color7="#cacabe"
color8="#8d8d85"
color9="#777B72"
color10="#948B77"
color11="#8FC17B"
color12="#3E8285"
color13="#458588"
color14="#749D91"
color15="#cacabe"
