--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kirk/Pictures/Wallpapers/space_wallhaven-gw96jd.jpg"

-- Special
background="#0a1018"
foreground="#c1c3c5"
cursor="#c1c3c5"

-- Colors
color0="#0a1018"
color1="#837C78"
color2="#7C837E"
color3="#89827D"
color4="#968F89"
color5="#A39C95"
color6="#AAA39C"
color7="#c1c3c5"
color8="#59626d"
color9="#837C78"
color10="#7C837E"
color11="#89827D"
color12="#968F89"
color13="#A39C95"
color14="#AAA39C"
color15="#c1c3c5"
