# pywal theme for ghostty

background = 1a0b0b
foreground = c5c2c2
cursor-color = c5c2c2
selection-background = c5c2c2
selection-foreground = 1a0b0b

palette = 0=#1a0b0b
palette = 1=#384367
palette = 2=#4A4F50
palette = 3=#62696C
palette = 4=#6A6F8E
palette = 5=#817D9A
palette = 6=#78868C
palette = 7=#c5c2c2
palette = 8=#6f5a5a
palette = 9=#384367
palette = 10=#4A4F50
palette = 11=#62696C
palette = 12=#6A6F8E
palette = 13=#817D9A
palette = 14=#78868C
palette = 15=#c5c2c2
