#!/bin/bash

# gum theme using pywal colors

# Confirm styles
export GUM_CONFIRM_PROMPT="? "
export GUM_CONFIRM_SELECTED_BACKGROUND="#83A598"
export GUM_CONFIRM_SELECTED_FOREGROUND="#101212"
export GUM_CONFIRM_UNSELECTED_BACKGROUND="#101212"
export GUM_CONFIRM_UNSELECTED_FOREGROUND="#c3c3c3"

# Input styles
export GUM_INPUT_CURSOR_FOREGROUND="#c3c3c3"
export GUM_INPUT_PROMPT_FOREGROUND="#478789"
export GUM_INPUT_PLACEHOLDER_FOREGROUND="#596d6d"
export GUM_INPUT_TEXT_FOREGROUND="#c3c3c3"
export GUM_INPUT_WIDTH=40

# Spinner styles
export GUM_SPIN_SPINNER_FOREGROUND="#C9D1A8"

# Filter styles
export GUM_FILTER_INDICATOR_FOREGROUND="#9EAA95"
export GUM_FILTER_SELECTED_PREFIX_FOREGROUND="#478789"
export GUM_FILTER_SELECTED_FOREGROUND="#c3c3c3"
export GUM_FILTER_UNSELECTED_PREFIX_FOREGROUND="#596d6d"

# Choose styles
export GUM_CHOOSE_CURSOR_FOREGROUND="#83A598"
export GUM_CHOOSE_SELECTED_FOREGROUND="#c3c3c3"
export GUM_CHOOSE_UNSELECTED_FOREGROUND="#596d6d"

# Write styles
export GUM_WRITE_CURSOR_FOREGROUND="#c3c3c3"
export GUM_WRITE_PROMPT_FOREGROUND="#478789"
