#!/bin/bash

# gum theme using pywal colors

# Confirm styles
export GUM_CONFIRM_PROMPT="? "
export GUM_CONFIRM_SELECTED_BACKGROUND="#7D8288"
export GUM_CONFIRM_SELECTED_FOREGROUND="#121212"
export GUM_CONFIRM_UNSELECTED_BACKGROUND="#121212"
export GUM_CONFIRM_UNSELECTED_FOREGROUND="#c3c3c3"

# Input styles
export GUM_INPUT_CURSOR_FOREGROUND="#c3c3c3"
export GUM_INPUT_PROMPT_FOREGROUND="#797C83"
export GUM_INPUT_PLACEHOLDER_FOREGROUND="#6e5959"
export GUM_INPUT_TEXT_FOREGROUND="#c3c3c3"
export GUM_INPUT_WIDTH=40

# Spinner styles
export GUM_SPIN_SPINNER_FOREGROUND="#999EA2"

# Filter styles
export GUM_FILTER_INDICATOR_FOREGROUND="#909499"
export GUM_FILTER_SELECTED_PREFIX_FOREGROUND="#797C83"
export GUM_FILTER_SELECTED_FOREGROUND="#c3c3c3"
export GUM_FILTER_UNSELECTED_PREFIX_FOREGROUND="#6e5959"

# Choose styles
export GUM_CHOOSE_CURSOR_FOREGROUND="#7D8288"
export GUM_CHOOSE_SELECTED_FOREGROUND="#c3c3c3"
export GUM_CHOOSE_UNSELECTED_FOREGROUND="#6e5959"

# Write styles
export GUM_WRITE_CURSOR_FOREGROUND="#c3c3c3"
export GUM_WRITE_PROMPT_FOREGROUND="#797C83"
