#!/bin/bash

# gum theme using pywal colors

# Confirm styles
export GUM_CONFIRM_PROMPT="? "
export GUM_CONFIRM_SELECTED_BACKGROUND="#879893"
export GUM_CONFIRM_SELECTED_FOREGROUND="#101213"
export GUM_CONFIRM_UNSELECTED_BACKGROUND="#101213"
export GUM_CONFIRM_UNSELECTED_FOREGROUND="#c3c3c4"

# Input styles
export GUM_INPUT_CURSOR_FOREGROUND="#c3c3c4"
export GUM_INPUT_PROMPT_FOREGROUND="#749190"
export GUM_INPUT_PLACEHOLDER_FOREGROUND="#59636e"
export GUM_INPUT_TEXT_FOREGROUND="#c3c3c4"
export GUM_INPUT_WIDTH=40

# Spinner styles
export GUM_SPIN_SPINNER_FOREGROUND="#AEA098"

# Filter styles
export GUM_FILTER_INDICATOR_FOREGROUND="#8CA799"
export GUM_FILTER_SELECTED_PREFIX_FOREGROUND="#749190"
export GUM_FILTER_SELECTED_FOREGROUND="#c3c3c4"
export GUM_FILTER_UNSELECTED_PREFIX_FOREGROUND="#59636e"

# Choose styles
export GUM_CHOOSE_CURSOR_FOREGROUND="#879893"
export GUM_CHOOSE_SELECTED_FOREGROUND="#c3c3c4"
export GUM_CHOOSE_UNSELECTED_FOREGROUND="#59636e"

# Write styles
export GUM_WRITE_CURSOR_FOREGROUND="#c3c3c4"
export GUM_WRITE_PROMPT_FOREGROUND="#749190"
